#!/usr/bin/env python3

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'nnsmith'))

from nnsmith.materialize.c import CModel
import pickle

def main():
    # Load the model
    with open('nnsmith_output/model.cmodel', 'rb') as f:
        ir = pickle.load(f)

    # Create C model and generate complete code
    c_model = CModel(ir)

    # Generate all parts of the C program
    imports = '\n'.join(c_model.import_libs)
    defs = c_model.emit_def('test_model', 'TestModel')
    execution = c_model.emit_run('output', 'test_model', 'input')
    weights = c_model.emit_weight('test_model')
    input_init = c_model.emit_input('input')

    # Write complete C program
    with open('generated/test_full_individual_vars.c', 'w') as f:
        f.write('/* Generated C Neural Network Program */\n')
        f.write('/* Generated by NNSmith C Backend */\n\n')
        f.write(imports)
        f.write('\n\n')
        f.write(defs)
        f.write('\n\n')
        f.write(weights)
        f.write('\n\n')
        f.write(input_init)
        f.write('\n\n')
        f.write(execution)

    print('Complete C code generated successfully!')

if __name__ == '__main__':
    main()