# Makefile for generated C neural network program
# Generated by NNSmith C Backend

CC = gcc
CFLAGS = -O2 -Wall -std=c99 -lm
TARGET = neural_network

# Default target
all: $(TARGET)

# Build the neural network program
$(TARGET): model.c
	$(CC) $(CFLAGS) -o $(TARGET) model.c

# Clean build artifacts
clean:
	rm -f $(TARGET) *.o

# Run with test data
run: $(TARGET)
	./$(TARGET)

# Install dependencies (placeholder)
install:
	@echo "No external dependencies required"

.PHONY: all clean run install
